### ISSUE TITLE
Rendere link non visibile

### ISSUE THREAD

**Issue by massi94** [Hexamini/PassioneKaraoke#83]
Secondo la WCAG [2.4.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-skip.html) #43 bisogna utilizzare un modo per fare il bypass di contenuti che si ripetono in ogni pagina per facilitare l'accesso a quelli che usano screen reader, bisogna quindi renderlo invisibile via CSS.
Nelle slide la gaggi dice di fare una cosa del genere:

``` css
.aiuti{
position:absolute;
height:0;
overflow:hidden
}
```
